### ISSUE TITLE
installation trouble

### ISSUE THREAD

**Issue by jsta** [sckott/dozedois#4]
I am having trouble installing. Do you have any ideas?

`$ rake install --trace`
> rake aborted!
LoadError: cannot load such file -- bundler/gem_tasks
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/jose/ruby/dozedois/Rakefile:1:in `<top (required)>'
/usr/lib/ruby/vendor_ruby/rake/rake_module.rb:28:in `load'
/usr/lib/ruby/vendor_ruby/rake/rake_module.rb:28:in `load_rakefile'
/usr/lib/ruby/vendor_ruby/rake/application.rb:689:in `raw_load_rakefile'
/usr/lib/ruby/vendor_ruby/rake/application.rb:94:in `block in load_rakefile'
/usr/lib/ruby/vendor_ruby/rake/application.rb:176:in `standard_exception_handling'
/usr/lib/ruby/vendor_ruby/rake/application.rb:93:in `load_rakefile'
/usr/lib/ruby/vendor_ruby/rake/application.rb:77:in `block in run'
/usr/lib/ruby/vendor_ruby/rake/application.rb:176:in `standard_exception_handling'
/usr/lib/ruby/vendor_ruby/rake/application.rb:75:in `run'
/usr/bin/rake:27:in `<main>'

`$ ruby --version` 
> ruby 2.3.0p0 (2015-12-25) [x86_64-linux-gnu]

`$ rake --version`
> rake, version 10.5.0

**Comment by sckott** [comment]
looking

**Comment by sckott** [comment]
@jsta what version of bundler do you have

**Comment by sckott** [comment]
able to reproduce with that ruby version, i was on 2.2.3, 

fixing some stuff

**Comment by jsta** [comment]
I solved it on my end. First I (re?)installed bundler and a ruby development environment:
> `$ sudo gem install bundler`
> `$ sudo apt-get install ruby-dev`

`$ rake install` was still giving me and error so I tried:
> `$ gem install /home/jose/ruby/dozedois/pkg/dozedois-0.0.9.gem`
> `ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /var/lib/gems/2.3.0 directory.`

which was solved by:
> `$ sudo rake install`

**Comment by sckott** [comment]
great, glad you sorted it out. I had to do the same, had to reinstall bundler after switching to ruby `v2.3.1`

I'll add to readme that `sudo` may be required 

note to self: https://github.com/bundler/bundler/issues/4602
